dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker 
  
before_install:
#   - git clone --recursive https://github.com/l19328/h3copenr
#   - git submodule init
#   - git submodule update
  - ls
  - pwd  
  - ls openr
  - ls h3cfibservice
  - ls comwaresdk
  - echo $GOPATH
  
install: 
  - ls /home/travis/gopath/src/
before_script:
  - ls /home/travis/gopath/src/
  
#script:
