dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker 
  
before_install:

install: true

before_script:
  - pwd
  - chmod a+x build/build.sh
  - ./build/build.sh
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - docker pull busybox
  - docker images
  - docker run -itd --name busybox busybox:latest 
  - docker ps
  - docker cp fibhandler busybox:/ 

  - docker exec busybox sh -c "./fibhandler -h"
  - docker exec busybox sh -c "ls"
  
script:

