dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker 
  
# before_install:
  
install: true

before_script:
  - pwd
  - chmod a+x build/build.sh
  - ./build/build.sh
  - pwd
#script:
