dist: xenial

language: go

go: 
  - 1.11.x

sudo: required

service:
  - docker 
  
before_install:

install: true

before_script:
  - pwd
  - chmod a+x build/build.sh
  - ./build/build.sh
  - cd /home/travis/gopath/src/github.com/h3copen/h3cfibservice/fibhandler
  - docker pull ubuntu:16.04
  - docker images
  - docker run -itd --name ubuntu1604 16.4:latest 
  - docker ps
  - docker cp fibhandler busybox:/ 
  - docker exec busybox sh -c "ls -l"
  - docker exec busybox sh -c "./fibhandler -h"

  
script:

